/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YachtsRouteImport } from './routes/yachts'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as RelocationRouteImport } from './routes/relocation'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as ChildbirthRouteImport } from './routes/childbirth'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as IndexRouteImport } from './routes/index'

const YachtsRoute = YachtsRouteImport.update({
  id: '/yachts',
  path: '/yachts',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const RelocationRoute = RelocationRouteImport.update({
  id: '/relocation',
  path: '/relocation',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildbirthRoute = ChildbirthRouteImport.update({
  id: '/childbirth',
  path: '/childbirth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/childbirth': typeof ChildbirthRoute
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/real-estate': typeof RealEstateRoute
  '/relocation': typeof RelocationRoute
  '/travel': typeof TravelRoute
  '/yachts': typeof YachtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/childbirth': typeof ChildbirthRoute
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/real-estate': typeof RealEstateRoute
  '/relocation': typeof RelocationRoute
  '/travel': typeof TravelRoute
  '/yachts': typeof YachtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/childbirth': typeof ChildbirthRoute
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/real-estate': typeof RealEstateRoute
  '/relocation': typeof RelocationRoute
  '/travel': typeof TravelRoute
  '/yachts': typeof YachtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/childbirth'
    | '/concierge'
    | '/contact'
    | '/real-estate'
    | '/relocation'
    | '/travel'
    | '/yachts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cars'
    | '/childbirth'
    | '/concierge'
    | '/contact'
    | '/real-estate'
    | '/relocation'
    | '/travel'
    | '/yachts'
  id:
    | '__root__'
    | '/'
    | '/cars'
    | '/childbirth'
    | '/concierge'
    | '/contact'
    | '/real-estate'
    | '/relocation'
    | '/travel'
    | '/yachts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsRoute: typeof CarsRoute
  ChildbirthRoute: typeof ChildbirthRoute
  ConciergeRoute: typeof ConciergeRoute
  ContactRoute: typeof ContactRoute
  RealEstateRoute: typeof RealEstateRoute
  RelocationRoute: typeof RelocationRoute
  TravelRoute: typeof TravelRoute
  YachtsRoute: typeof YachtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yachts': {
      id: '/yachts'
      path: '/yachts'
      fullPath: '/yachts'
      preLoaderRoute: typeof YachtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relocation': {
      id: '/relocation'
      path: '/relocation'
      fullPath: '/relocation'
      preLoaderRoute: typeof RelocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/childbirth': {
      id: '/childbirth'
      path: '/childbirth'
      fullPath: '/childbirth'
      preLoaderRoute: typeof ChildbirthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsRoute: CarsRoute,
  ChildbirthRoute: ChildbirthRoute,
  ConciergeRoute: ConciergeRoute,
  ContactRoute: ContactRoute,
  RealEstateRoute: RealEstateRoute,
  RelocationRoute: RelocationRoute,
  TravelRoute: TravelRoute,
  YachtsRoute: YachtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
